export const catchAsyncErrors = (thefunction) => {
    return ()
}